[window]
  padding = {x =5, y = 5}

[font]
  offset = {y=5}
  size = 13

  glyph_offset = {y=5}

[colors]
  [colors.primary]
    foreground = '#ffffff'
  [colors.secondary]
    foreground = '#4682B4'

[window]
  decorations = 'Buttonless'
  opacity = 0.9
